### PR TITLE
Remodel Event Generator as a Capture

### PR DESCRIPTION
**Pull request by saterus**
The original event generator script left a few things to be desired:
1. It sent data to Flow using the `flow-ingester`, which isn't listed as a Capture in the `.flow.yaml`. This is an implicit data source, which requires new users need to understand yet another piece of the Flow ecosystem.
1. It required new users to run it as a 3rd script in yet another terminal.

Moving the event generator to an Airbyte-compatible Connector allows us to configure it in the `1_capture.flow.yaml` alongside the rest of the Flow Catalog. This solves both shortcomings:
1. It's listed in the `.flow.yaml`, which is the expected workflow moving forward.
2. It begins running as soon as `flowctl develop` boots up without any extra input from the user.

---
This change is [Reviewable](https://reviewable.io/reviews/estuary/demos-segmentation/2)

### CODE REVIEW

**Comment by saterus** [comment]
I think we'll need to create a package in ghcr to allow us to push the `event-generator` image. I don't appear to have the right permissions for that.

I wasn't *planning* to add an automated workflow to push it since we will also need to update the `1_capture.flow.yaml` reference as well. I was just assuming we'd push it from our laptops when making future updates.

**Review by jgraettinger — APPROVED** [review]
Awesome, for being new to Go this is a really polished PR. Some comments below which are hopefully helpful.

LGTM % `maxEventsPerSecond` comment. Everything else here is just picking nits

> Reviewed 18 of 18 files at r1.
> *[Reviewable](https://reviewable.io/reviews/estuary/demos-segmentation/2#-:-MfjTEil370MdZCvsQOo:bsjpr8q)* status: all files reviewed, 10 unresolved discussions (waiting on @saterus)

___
*[1_capture.flow.yaml, line 7 at r1](https://reviewable.io/reviews/estuary/demos-segmentation/2#-MfjM5DhAvPExF7I5cEb:-MfjM5Di-Gi7aIIVOl-5:bizz361) ([raw file](https://github.com/estuary/demos-segmentation/blob/a72171149906ddea034a28f9f4101a9ab9107ff0/1_capture.flow.yaml#L7)):*
> ```YAML
>         image: ghcr.io/estuary/demos-segmentation-event-generator:ad05fa1
>         config:
>           maxEventsPerSecond: 5
> ```

Qualitatively this should be about 1K events per second for enough interesting downstream stuff to happen as part of a demo script. That way refreshes of SQL queries every few seconds are visually different 
___
*[event-generator/main.go, line 9 at r1](https://reviewable.io/reviews/estuary/demos-segmentation/2#-MfjPZkQ3oFrt5yM9gAe:-MfjPZkQ3oFrt5yM9gAf:batgfon) ([raw file](https://github.com/estuary/demos-segmentation/blob/a72171149906ddea034a28f9f4101a9ab9107ff0/event-generator/main.go#L9)):*
> ```Go
> 
> 	"github.com/estuary/connectors/go-types/airbyte"
> 	"github.com/estuary/demos-segmentation/event-generator/events"
> ```

It's probably overkill to start breaking this into packages at this stage, given generating events is the whole point of this program and the `events` package has no utility outside of this program.

As compared to Rust, where these would totally make sense as separate modules, it's typically a higher bar before code gets broken out into separate Go packages. And it's typically motivated because you expect there are _other_ packages which want to use that code. You can instead, for example, move events.go into this `main` package with private (non Capitalized) definitions.
___
*[event-generator/main.go, line 13 at r1](https://reviewable.io/reviews/estuary/demos-segmentation/2#-MfjQuTcE3Df-53uhFJH:-MfjQuTcE3Df-53uhFJI:b-yyaodw) ([raw file](https://github.com/estuary/demos-segmentation/blob/a72171149906ddea034a28f9f4101a9ab9107ff0/event-generator/main.go#L13)):*
> ```Go
> )
> 
> type Config struct {
> ```

As a general rule, any Capitalized (exported) definition like `Config` should have doc comments. I'd recommend getting a linter set up because it will give you warnings on this.  I would keep this private as `config`.
___
*[event-generator/main.go, line 57 at r1](https://reviewable.io/reviews/estuary/demos-segmentation/2#-MfjO0Rg-q07tSTfAupl:-MfjO0Rg-q07tSTfAupm:b-u1b9e6) ([raw file](https://github.com/estuary/demos-segmentation/blob/a72171149906ddea034a28f9f4101a9ab9107ff0/event-generator/main.go#L57)):*
> ```Go
> 			"title":       "Number of Events per Second",
> 			"description": "Maximum number of Events produced per second",
> 			"default":     "10"
> ```

1k here too. I don't think we're _too_ far off from wiring up `default` into generated placeholders in the discovery workflow.
___
*[event-generator/main.go, line 62 at r1](https://reviewable.io/reviews/estuary/demos-segmentation/2#-MfjRO-CDdzdfHgrNFty:-MfjRO-CDdzdfHgrNFtz:bac4046) ([raw file](https://github.com/estuary/demos-segmentation/blob/a72171149906ddea034a28f9f4101a9ab9107ff0/event-generator/main.go#L62)):*
> ```Go
> }`
> 
> type State struct {
> ```

as with `Config`, this shouldn't be exported (and if it were, it needs a doc comment).
___
*[event-generator/main.go, line 133 at r1](https://reviewable.io/reviews/estuary/demos-segmentation/2#-MfjOK1oDiDQH7LNYZer:-MfjOK1oDiDQH7LNYZes:b-29p34u) ([raw file](https://github.com/estuary/demos-segmentation/blob/a72171149906ddea034a28f9f4101a9ab9107ff0/event-generator/main.go#L133)):*
> ```Go
> 	}
> 
> 	var enc *json.Encoder = airbyte.NewStdoutEncoder()
> ```

optional nit: there's also a
```
var (
  thingOne theType,
  thingTwo = someFunc(),
)
```
syntax which `gofmt` will nicely align.

The `func(*State) error` declarations aren't necessary, but are also perhaps helpful to the reader, which I'm guessing is what you were going for (and :thumbsup: in that regard)
___
*[event-generator/main.go, line 155 at r1](https://reviewable.io/reviews/estuary/demos-segmentation/2#-MfjRdus2el3JD0OWKoG:-MfjRdus2el3JD0OWKoH:b6k4vnb) ([raw file](https://github.com/estuary/demos-segmentation/blob/a72171149906ddea034a28f9f4101a9ab9107ff0/event-generator/main.go#L155)):*
> ```Go
> }
> 
> func buildEventProducer(enc *json.Encoder, eventSource events.Source) func(*State) error {
> ```

It's not clear that the use of a closure is buying anything here. Why not a non-closure function taking |enc|, |eventSource|, and |state| ?

|event| doesn't need to be closed over because it's value isn't being re-used between invocations of the returned closure.
___
*[event-generator/main.go, line 172 at r1](https://reviewable.io/reviews/estuary/demos-segmentation/2#-MfjS-iR6p8cvA8lrBz5:-MfjS-iR6p8cvA8lrBz6:b-iqwjxx) ([raw file](https://github.com/estuary/demos-segmentation/blob/a72171149906ddea034a28f9f4101a9ab9107ff0/event-generator/main.go#L172)):*
> ```Go
> 
> func buildCheckpointer(enc *json.Encoder) func(*State) error {
> 	var throttler throttle.Throttler = throttle.New(200 * time.Millisecond)
> ```

As compared to `buildEventProducer`, this use of a closure makes sense to me since |throttler| is an inner state. I _might_ still just hoist |throttler| to the parent function and pass by argument rather than using a closure, but it's fine either way.
___
*[event-generator/events/events.go, line 34 at r1](https://reviewable.io/reviews/estuary/demos-segmentation/2#-MfjSoXz1aKkwT6K5XSO:-MfjSoXz1aKkwT6K5XSP:b-fprkx4) ([raw file](https://github.com/estuary/demos-segmentation/blob/a72171149906ddea034a28f9f4101a9ab9107ff0/event-generator/events/events.go#L34)):*
> ```Go
> )
> 
> type Segment struct {
> ```

more places which can be nonCapitalized private vs Public.
___
*[event-generator/throttle/throttle.go, line 1 at r1](https://reviewable.io/reviews/estuary/demos-segmentation/2#-MfjT1EBEbJw1jm3QWIM:-MfjT1EBEbJw1jm3QWIN:b-dx1mhl) ([raw file](https://github.com/estuary/demos-segmentation/blob/a72171149906ddea034a28f9f4101a9ab9107ff0/event-generator/throttle/throttle.go#L1)):*
> ```Go
> package throttle
> ```

as discussed, this is good but better to use the `rate` package

**Review by jgraettinger — COMMENTED** [review]
Also, updated permissions, should be good now.

> *[Reviewable](https://reviewable.io/reviews/estuary/demos-segmentation/2#-:-MfjU9_r48BV29eteVQu:bmgfvug)* status: all files reviewed, 10 unresolved discussions (waiting on @saterus)

**Review by saterus — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/estuary/demos-segmentation/2)* status: all files reviewed, 10 unresolved discussions (waiting on @jgraettinger and @saterus)

___
*[1_capture.flow.yaml, line 7 at r1](https://reviewable.io/reviews/estuary/demos-segmentation/2#-MfjM5DhAvPExF7I5cEb:-Mfn-SsJELrMP8IFFedu:b-rdfrbf) ([raw file](https://github.com/estuary/demos-segmentation/blob/a72171149906ddea034a28f9f4101a9ab9107ff0/1_capture.flow.yaml#L7)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

Qualitatively this should be about 1K events per second for enough interesting downstream stuff to happen as part of a demo script. That way refreshes of SQL queries every few seconds are visually different 
</blockquote></details>

Gotcha. I had it low because when you run the generator by itself it fills the terminal so quickly it's hard to realize the data is changing. :sweat_smile: I wasn't checking the SQL queries very frequently when working through this.
___
*[event-generator/main.go, line 9 at r1](https://reviewable.io/reviews/estuary/demos-segmentation/2#-MfjPZkQ3oFrt5yM9gAe:-Mfn0Tv18pZ5V2Lq6eZ3:b-y4mb4o) ([raw file](https://github.com/estuary/demos-segmentation/blob/a72171149906ddea034a28f9f4101a9ab9107ff0/event-generator/main.go#L9)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

It's probably overkill to start breaking this into packages at this stage, given generating events is the whole point of this program and the `events` package has no utility outside of this program.

As compared to Rust, where these would totally make sense as separate modules, it's typically a higher bar before code gets broken out into separate Go packages. And it's typically motivated because you expect there are _other_ packages which want to use that code. You can instead, for example, move events.go into this `main` package with private (non Capitalized) definitions.
</blockquote></details>

Yeah, this was strictly an internal organization thing rather than an issue of reuse. I was looking at the 400 line file and realized half of it was about _generating_ the events and half was Airbyte-connector glue, which seemed like a reasonable boundary to draw. I saw that you can split a single package into multiple files, but there's no effect on the privacy of items.
___
*[event-generator/main.go, line 13 at r1](https://reviewable.io/reviews/estuary/demos-segmentation/2#-MfjQuTcE3Df-53uhFJH:-Mfn1IX10TTJPtcMkkkZ:b-hlkg5e) ([raw file](https://github.com/estuary/demos-segmentation/blob/a72171149906ddea034a28f9f4101a9ab9107ff0/event-generator/main.go#L13)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

As a general rule, any Capitalized (exported) definition like `Config` should have doc comments. I'd recommend getting a linter set up because it will give you warnings on this.  I would keep this private as `config`.
</blockquote></details>

Yeah, I'd simply forgotten to adjust this after cribbing it from the `source-hello-world` connector.
___
*[event-generator/main.go, line 57 at r1](https://reviewable.io/reviews/estuary/demos-segmentation/2#-MfjO0Rg-q07tSTfAupl:-Mfn-vGa3Sd4ICHMRnjj:b-ygdtun) ([raw file](https://github.com/estuary/demos-segmentation/blob/a72171149906ddea034a28f9f4101a9ab9107ff0/event-generator/main.go#L57)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

1k here too. I don't think we're _too_ far off from wiring up `default` into generated placeholders in the discovery workflow.
</blockquote></details>

Yeah, I think I tweaked them in the generator after creating the yaml and forgot to sync them back up.
___
*[event-generator/main.go, line 133 at r1](https://reviewable.io/reviews/estuary/demos-segmentation/2#-MfjOK1oDiDQH7LNYZer:-Mfn06rxBqOMaaeScob8:bh9ztkd) ([raw file](https://github.com/estuary/demos-segmentation/blob/a72171149906ddea034a28f9f4101a9ab9107ff0/event-generator/main.go#L133)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

optional nit: there's also a
```
var (
  thingOne theType,
  thingTwo = someFunc(),
)
```
syntax which `gofmt` will nicely align.

The `func(*State) error` declarations aren't necessary, but are also perhaps helpful to the reader, which I'm guessing is what you were going for (and :thumbsup: in that regard)
</blockquote></details>

Gotcha. I sort of expected that if it was the preferable way to write it, `gofmt` would have restructured it for me. It seems to do more aggressive changes than I'd normally expect from a formatter. :upside_down_face: 

Yes, the explicit annotations were just for the reader, not the compiler.
___
*[event-generator/main.go, line 155 at r1](https://reviewable.io/reviews/estuary/demos-segmentation/2#-MfjRdus2el3JD0OWKoG:-Mfn1W_2CR1PdzxzHXcY:b-c43ea4) ([raw file](https://github.com/estuary/demos-segmentation/blob/a72171149906ddea034a28f9f4101a9ab9107ff0/event-generator/main.go#L155)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

It's not clear that the use of a closure is buying anything here. Why not a non-closure function taking |enc|, |eventSource|, and |state| ?

|event| doesn't need to be closed over because it's value isn't being re-used between invocations of the returned closure.
</blockquote></details>

Yeah, I think this was mostly playing with the tools available to me. An artifact of a series of gradual changes. They'd be functionally equivalent.
___
*[event-generator/main.go, line 172 at r1](https://reviewable.io/reviews/estuary/demos-segmentation/2#-MfjS-iR6p8cvA8lrBz5:-Mfn1p2HANn5YMlY-oUJ:bdkrvdd) ([raw file](https://github.com/estuary/demos-segmentation/blob/a72171149906ddea034a28f9f4101a9ab9107ff0/event-generator/main.go#L172)):*
<details><summary><i>Previously, jgraettinger (Johnny Graettinger) wrote…</i></summary><blockquote>

As compared to `buildEventProducer`, this use of a closure makes sense to me since |throttler| is an inner state. I _might_ still just hoist |throttler| to the parent function and pass by argument rather than using a closure, but it's fine either way.
</blockquote></details>

Yeah, that's exactly where it started. I was trying to push the responsibility for _deciding_ to emit a state message into the checkpoint function, rather than have the caller know it needs to keep a ticker around for that purpose.

**Comment by saterus** [comment]
@jgraettinger Re: GitHub Docker Registry: 

I still can't create a new package, either from the CLI or from https://github.com/orgs/estuary/packages.

That said, I've noticed that we're using ghcr.io for the estuary/connectors, but quay.io for estuary/flow. Is there one that should be preferred moving forward?

**Pull request merged**
